spring:
  application:
    name: chb
  profiles:
    active: dev # 기본 활성 프로필을 'dev'로 설정
  datasource:
    # 4. Oracle JDBC 드라이버 클래스 이름
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    # JPA/Hibernate settings for Oracle
    database-platform: org.hibernate.dialect.OracleDialect