spring:
  application:
    name: chb
  datasource:
    # 4. Oracle JDBC 드라이버 클래스 이름
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    # JPA/Hibernate settings for Oracle
    database-platform: org.hibernate.dialect.OracleDialect 