spring:
  application:
    name: chb
  # profiles:
  #   active: dev   # dev 프로필을 기본값으로 설정
  datasource:
    # 4. Oracle JDBC 드라이버 클래스 이름
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    # JPA/Hibernate settings for Oracle
    database-platform: org.hibernate.dialect.OracleDialect
    properties:
      hibernate:
        jdbc: 
          time_zone: Asia/Seoul